import { useEffect } from "react";
import { Link } from "react-router-dom";
import NewsImage from "../../assets/images/news-2.png";
import { BsArrowRight } from "react-icons/bs";

function PublicationDetail() {
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
  }, [])

  return (
    <div className="container mx-auto px-32">
      <h3 className="text-black text-3xl text-center font-bold leading-[60px] sm:px-16 lg:px-32">Considerations for an integrated population health databank in Africa: lessons from global best practices [version 1; peer review: 2 approved]</h3>
      <div className="my-16 w-full lg:w-[60%] mx-auto">
        <img src={NewsImage} alt="News Image" className="w-full h-auto rounded-xl" />
      </div>
      <div className="px-4 sm:px-16 lg:px-32">
        <p className="text-[#333333] text-xl font-normal leading-[30px] sm:leading-[45px]"><strong className="text-[#333333] text-3xl leading-[40px]">Abstract</strong><br />
          Background: The rising digitisation and proliferation of data sources and repositories cannot be ignored. This trend expands opportunities to integrate and share population health data. Such platforms have many benefits, including the potential to efficiently translate information arising from such data to evidence needed to address complex global health challenges. There are pockets of quality data on the continent that may benefit from greater integration. Integration of data sources is however under-explored in Africa. The aim of this article is to identify the requirements and provide practical recommendations for developing a multi-consortia public and population health data-sharing framework for Africa.Methods: We conducted a narrative review of global best practices and policies on data sharing and its optimisation. We searched eight databases for publications and undertook an iterative snowballing search of articles cited in the identified publications. The Leximancer software © enabled content analysis and selection of a sample of the most relevant articles for detailed review. Themes were developed through immersion in the extracts of selected articles using inductive thematic analysis. We also performed interviews with public and population health stakeholders in Africa to gather their experiences, perceptions, and expectations of data sharing.Results: Our findings described global stakeholder experiences on research data sharing. We identified some challenges and measures to harness available resources and incentivise data sharing. We further highlight progress made by the different groups in Africa and identified the infrastructural requirements and considerations when implementing data sharing platforms. Furthermore, the review suggests key reforms required, particularly in the areas of consenting, privacy protection, data ownership, governance, and data access.Conclusions: The findings underscore the critical role of inclusion, social justice, public good, data security, accountability, legislation, reciprocity, and mutual respect in developing a responsive, ethical, durable, and integrated research data sharing ecosystem.</p>
        <br />
        <p className="text-[#333333] text-xl font-normal leading-[30px] sm:leading-[45px]"><strong className="text-[#333333] text-3xl leading-[40px]">Introduction</strong><br />
          The public and population health research and development landscape in Africa has seen an increase in publications and the maturation of mostly donor-funded development programmes, research projects and multi-disciplinary capacity building networks1–9. These programmes collect and generate data that could be collated, integrated, or triangulated to address the complex and inter-related public and population health challenges in Africa. Health research data collation and sharing programmes are already in place in many high-income countries. Examples include the BigData@Heart platform of the European Union’s (EU) Innovative Medicine Initiative10, the EU’s Horizon 2020 Project and Open Science Cloud11, and others12–15.
          The growth of databanks and repositories has expanded opportunities for data sharing to advance global health. These platforms16 are setup to generate evidence-driven translation of research10 which enhance our understanding of and response to public health challenges. This, in turn, can improve public health training and service delivery, and speed up health innovation. Health data integration and use is equally important in strengthening health systems. It can generate evidence-informed solutions; inform the roles and choices of patients and service providers; spur discovery to improve patient care; and help evaluate the outcome of health services and health capacity and research building programmes17.
          Despite the improvements of the last decades, Africa still lags behind in research and development - contributing less than 2% of global research output18. While the reasons are manifold19, the situation is compounded by the lack of (or limited) African-led databanks or data repositories platforms. This hampers data sharing, reuse, integration, meta-analyses, and cross-referencing. Digitisation, integration, and information sharing may allow Africa to generate knowledge more rapidly to address its public health challenges.
          A vision of an African integrated databank is mindful of related challenges. These include data privacy, malicious use of data, complexities of regulating digital information, fragmented privacy regulations and jurisdictional nuances, and lack of acknowledgement of researchers and scientists20–25. Additionally, conventional informed consent and human research ethics committees (RECs) must consider emerging issues of data stewardship such as the longer storage, sharing, re-identification and indeterminate future use of collected data26–30.
          The main objective of this article is to provide practical recommendations and requirements to support the development of a multi-consortia public and population health data sharing framework for Africa. This research seeks to inform a platform that will harnesses available resources, incentivise data sharing, and optimise the progress made by different research groups in Africa. The review draws on a collection of global best practices and policies. With this research, we address the challenges and misconceptions of data sharing in Africa. The collection of global stakeholder experiences on research data sharing presented here offers essential discussion points for consideration in developing an integrated population health databank in Africa. This article, therefore, targets all who are impacted by research data sharing or stand to gain from an understanding of the key tenets to consider when sharing research data in the context of privacy, confidentiality, information security and respect of human data and biological specimens.
        </p>
        <br />
        <p className="text-[#333333] text-xl font-normal leading-[30px] sm:leading-[45px]"><strong className="text-[#333333] text-3xl leading-[40px]">Methods</strong><br />
          <strong className="text-[#333333] text-xl leading-[40px]">Narrative review</strong><br />
          We undertook a narrative review of publications and policy documents on data sharing in public and population health.
          The methodological standards of narrative reviews described by Greenhalgh et al.31 and noted as best suited for exploring broad and complex topics using a constructivist philosophy32 were followed. Inclusion of policy documents in this review is a common practice under these circumstances33. Inclusion of policy documents is also informed by the strong policy foundation of the topic, and the expectation that this review may inform future policies on data sharing. We searched eight databases for publications, namely PubMed, EMBASE, PsycINFO, Joanna Briggs, The Cochrane Library, EBM reviews, Scopus, and Web of Science. We did not set any time frames so as to include historic patterns, which may inform current data sharing practices. Our data search included all articles related to “population health data sharing” and “public health data sharing”. We also followed-up articles cited in the papers we identified in our initial search to ensure relevance of the review to our target audience31,34. The search process was, therefore, an iterative snowballing exercise.
          Our initial search identified 3825 articles that were loaded into Mendeley to remove duplicates. Two independent reviewers (JOI and ENB) evaluated the title and abstract of each article to assess its relevance for inclusion in our review. This approach did not rely on a pre-defined keyword search to identify conceptually and empirically relevant documents. Any disagreements between the reviewers were resolved through discussions among the review team. We followed a qualitative appraisal based on principles of pragmatism, pluralism, historicity, contestation and reflexivity31,34. At the end, we identified 655 documents for further review.
          The Leximancer software © Version 5 enabled content analysis and selection of a sample of articles for detailed review35,36. Leximancer like alternative software (such as Nvivo and MXQDA) are all paid-to-use software with limited trial period. Leximancer identifies lexical co-occurrence of natural language into semantic patterns37. It is reproducible and uses an unsupervised machine learning model that is built on Bayesian Theory to predict events based on an observed pattern35,37. Leximancer identified seven core themes from the 655 articles selected. We extracted and reviewed articles with the highest co-count and likelihood of containing each theme in their segments. We selected as many as 20 articles per theme based on our reaching saturation after reading on average, the top 15 articles. Our selection of articles also involved full-text screening.<br />
          <strong className="text-[#333333] text-xl leading-[40px]">Interview with key information</strong><br />
          To ensure that our approach to the literature addressed the concerns and questions of local African stakeholders, we had interviews with 35 key informants from African-led research and capacity building programmes who produce population and public health data that could be included in a shared database. To identify these consortia we took advantage of the range of African-led programmes funded by the Alliance for Accelerating Excellence in Science in Africa (AESA)38. Participants were purposively sampled, which created a diverse group, ranging from basic science and genomics to applied translation science. In-depth interviews of about 60 to 90 minutes were conducted virtually using Microsoft teams. We used an open-ended guide (see Extended data39) to facilitate the interviews, but the discussions were flexible, with the interviewee responses shaping the discussions. We obtained a written consent to participate in the interviews from the participants. Eleven out of the 35 participants declined being recorded and notes were taken during their interview. Twenty-four interviews were audio-recorded and transcribed, and summary of emerging themes were discussed with the participants at the end of each interview. Summaries from all interviews were compiled into key themes and sub-themes. The finding of interviews presented in this paper are highly consolidated and pose no risk to the expert informants interviewed; therefore, ethical approval was not required to be obtained.
          In all, the views expressed in the paper are completely based on review of literature that is available in public domain. The informal and internal consultations with network peers that constituted the interviews were used to position our findings. The consultations were also to ensure the literature review’s regional relevance, and to promote objectivity and reflexivity in our analysis and interpretation of findings. The interviews, literature review and initial analysis were conducted by two of the authors (a male and a female) with PhD in Public Health and Medical Anthropology, respectively. They have training and experience in qualitative research, ethics, epidemiology, and data science.
        </p>

        <Link to="/news" className="relative flex flex-row items-center w-fit z-10 underline text-[#1BAE70] hover:text-[#333333] text-2xl xl:text-3xl font-normal leading-[40px] my-16  transition ease-in-out duration-300">
          Back to News and articles <BsArrowRight className="ml-4" />
        </Link>
      </div>
    </div>
  )
}

export default PublicationDetail;