export const data = {
    "users": [
      {
        "id": 1,
      "region": "East",
      "location": "Ethiopia",
      "economic": "LIC",
      "name_of_cohort": "Harar HDSS",
      "type": "HDSS",
      "description": "Urban HDSS",
      "area": "Harar city",
      "HDSS": "Y",
      "biosamoles": "N",
      "N": "63000",
      "setting": "Urban",
      "research": "",
      "networks": "INDEPTH",
      "follow_up": "2011-ongoing",
      "institution": "College of Health and Medical Sciences, Haramaya University",
      "website": "http://researchaffairs.haramaya.edu.et/wp-content/uploads/2017/09/18-Kersa-Harar-HDSS.pdf",
      "contact": "negaassefa@yahoo.com",
      "added_by": "Scoping doc",
      "notes": ""
      },
      {
        "id": 2,
      "region": "East",
      "location": "Ethiopia",
      "economic": "LIC",
      "name_of_cohort": "Young Lives",
      "type": "Birth cohort",
      "description": "Birth cohort now adult and older cohort of 1000 who were 8 years old when the study began enabling comparisons of ages 8, 12, 15 and 19",
      "area": "Amhara, Oromia, SNNPR, Tigray, Addis Ababa and Sidama",
      "HDSS": "",
      "biosamoles": "N",
      "N": "3000",
      "setting": "Rural and Urban",
      "research": "",
      "networks": "",
      "follow_up": "2002-ongoing",
      "institution": "Policy Studies Institute",
      "website": "https://www.younglives-ethiopia.org/young-lives-ethiopia-home",
      "contact": "alulap@gmail.com",
      "added_by": "Scoping doc",
      "notes": ""
      },
      {
        "id": 3,
      "region": "East",
      "location": "Ethiopia",
      "economic": "LIC",
      "name_of_cohort": "Kersa HDSS",
      "type": "HDSS",
      "description": "Rural/Urban HDSS",
      "area": "Kersa district",
      "HDSS": "HDSS",
      "biosamoles": "No",
      "N": "132000",
      "setting": "Rural and urban",
      "research": "Y",
      "networks": "INDEPTH",
      "follow_up": "2007-ongoing",
      "institution": "Haramaya University",
      "website": "Research News � HU (haramaya.edu.et)",
      "contact": "negaassefa@yahoo.com",
      "added_by": "",
      "notes": "Started in 2007"
      },
      {"id": 4,
      "region": "East",
      "location": "Ethiopia",
      "economic": "LIC",
      "name_of_cohort": "Haramaya HDSS",
      "type": "HDSS",
      "description": "Rural HDSS",
      "area": "Haramaya district",
      "HDSS": "HDSS",
      "biosamoles": "No",
      "N": "91000",
      "setting": "Rural",
      "research": "Y",
      "networks": "",
      "follow_up": "2019-ongoing",
      "institution": "Haramaya University",
      "website": "https://www.hararghe.org/research-sites",
      "contact": "negaassefa@yahoo.com",
      "added_by": "",
      "notes": "Started in 2019"
      },
      {
        "id": 5,
      "region": "East",
      "location": "Kenya",
      "economic": "LMIC",
      "name_of_cohort": "Kilifi HDSS - waiting from PI",
      "type": "HDSS",
      "description": "Rural KHDDSS,linked with clinical survellaince",
      "area": "Kilifi",
      "HDSS": "Y",
      "biosamoles": "Y",
      "N": "310000",
      "setting": "Rural",
      "research": "Y",
      "networks": "INDEPTH",
      "follow_up": "2000-ongoing",
      "institution": "KEMRI-Wellcome Trust",
      "website": "https://kemri-wellcome.org/",
      "contact": "Anthony.Scott@lshtm.ac.uk",
      "added_by": "DK,",
      "notes": ""
      },
      {
        "id": 6,
      "region": "East",
      "location": "Kenya",
      "economic": "LMIC",
      "name_of_cohort": "Nairobi Urban HDSS",
      "type": "HDSS",
      "description": "Urban HDSS",
      "area": "Nairobi",
      "HDSS": "Y",
      "biosamoles": "N",
      "N": "90000",
      "setting": "Urban",
      "research": "Y",
      "networks": "INDEPTH/INSPIRE",
      "follow_up": "2002-2020",
      "institution": "African Population and Health Research Centre",
      "website": "Nairobi Urban Health and Demographic Surveillance System (NUHDSS) - APHRC",
      "contact": "mwamukoya@aphrc.org",
      "added_by": "",
      "notes": "We paused the NUHDSS in March 2020 in order to re-design and re-launch it"
      },
      {
        "id": 7,
      "region": "East",
      "location": "Kenya",
      "economic": "LMIC",
      "name_of_cohort": "Kagondo HDSS",
      "type": "HDSS",
      "description": "Open population cohort",
      "area": "Kasese",
      "HDSS": "HDSS",
      "biosamoles": "No",
      "N": "30000",
      "setting": "Rural",
      "research": "Y",
      "networks": "",
      "follow_up": "2017-ongoing",
      "institution": "Kagando Hospital but soon to be run by Kasese Research Institute under registration",
      "website": "",
      "contact": "asinjakapuru@gmail.com",
      "added_by": "",
      "notes": "Started in 2017"
      },
      {
        "id": 8,
      "region": "East",
      "location": "Kenya",
      "economic": "LMIC",
      "name_of_cohort": "Kaloleni/Rabai",
      "type": "Community HDSS",
      "description": "Rural HDSS",
      "area": "Kaloleni and Rabai subcounties",
      "HDSS": "Y",
      "biosamoles": "No",
      "N": "98871",
      "setting": "Peri-urban and rural township areas",
      "research": "Y",
      "networks": "INSPIRE",
      "follow_up": "2017-ongoing",
      "institution": "Aga Khan University",
      "website": "",
      "contact": "rosebella.ondiek@aku.edu",
      "added_by": "",
      "notes": "Started in 2017"
      },
      {
        "id": 9,
      "region": "East",
      "location": "Madagascar",
      "economic": "LIC",
      "name_of_cohort": "IHOPE",
      "type": "Cohort",
      "description": "Household level longitudinal cohort",
      "area": "Ifanadiana District",
      "HDSS": "",
      "biosamoles": "Y",
      "N": "10508",
      "setting": "Rural",
      "research": "N",
      "networks": "",
      "follow_up": "2014-ongoing",
      "institution": "PIVOT",
      "website": "Pivot | IHOPE (household � longitudinal cohort) (pivotworks.org)",
      "contact": "ann_miller@hms.harvard.edu",
      "added_by": "",
      "notes": ""
      },
      {
        "id": 10,
      "region": "East",
      "location": "Mozambique",
      "economic": "LIC",
      "name_of_cohort": "Manhica HDSS",
      "type": "HDSS",
      "description": "Rural HDSS",
      "area": "Manhica District",
      "HDSS": "Y",
      "biosamoles": "N",
      "N": "212305",
      "setting": "Rural",
      "research": "Y",
      "networks": "INDEPTH/CHAMPS",
      "follow_up": "1996-ongoing",
      "institution": "Manhica Health Research Centre",
      "website": "",
      "contact": "charfudin.sacoor@manhica.net",
      "added_by": "",
      "notes": ""
      },
      {
        "id": 11,
      "region": "East",
      "location": "Tanzania",
      "economic": "LMIC",
      "name_of_cohort": "Kisesa (Magu HDSS)",
      "type": "HDSS",
      "description": "Observational HIV cohort that includes Magu DHSS",
      "area": "Magu District",
      "HDSS": "Y",
      "biosamoles": "Y",
      "N": "About 45,000",
      "setting": "Rural",
      "research": "Y",
      "networks": "ALPHA, INSPIRE, INDEPTH and IeDEA",
      "follow_up": "1994-ongoing",
      "institution": "NIMR, Mwanza Centre",
      "website": "mwanza@nimr.or.tz",
      "contact": "urassamark62@gmail.com",
      "added_by": "Jim Todd",
      "notes": "The site has three major activities: 1. Research i.e. HDSS, Sero survey & nested studies). 2. Interventions against HIV Epidemic & other diseases. 3. Service to the community health systen, education and general support to the community developmental activities."
      },
      {
        "id": 12,
      "region": "East",
      "location": "Uganda",
      "economic": "LIC",
      "name_of_cohort": "General Population Cohort",
      "type": "Cohort",
      "description": "Rural HDSS",
      "area": "Kalungu district",
      "HDSS": "Nested within Kyamulibwa",
      "biosamoles": "Y",
      "N": "22000",
      "setting": "Rural",
      "research": "Y",
      "networks": "",
      "follow_up": "1989-ongoing",
      "institution": "MRC/LSHTM Uganda",
      "website": "",
      "contact": "joseph.mugisha@mrcuganda.org",
      "added_by": "",
      "notes": ""
      },
      {
        "id": 13,
      "region": "Eastern",
      "location": "Uganda",
      "economic": "LMIC",
      "name_of_cohort": "Eldery Cohort of Persons living with HIV in Uganda",
      "type": "Cohort",
      "description": "Clinical cohort",
      "area": "Central Kampala",
      "HDSS": "N",
      "biosamoles": "Yes",
      "N": "500",
      "setting": "Urban",
      "research": "",
      "networks": "",
      "follow_up": "2019-ongoing",
      "institution": "Infectious Diseases Institute, Makerere",
      "website": "",
      "contact": "bcastelnuovo@idi.co.ug",
      "added_by": "",
      "notes": "Started 2019"
      },
      {
        "id": 14,
      "region": "Eastern",
      "location": "Uganda",
      "economic": "LMIC",
      "name_of_cohort": "Adult Longitudinal HIV cohort",
      "type": "Cohort",
      "description": "Clinical cohort",
      "area": "Central Kampala",
      "HDSS": "N",
      "biosamoles": "Yes",
      "N": "1000",
      "setting": "Urban",
      "research": "",
      "networks": "",
      "follow_up": "2005-ongoing",
      "institution": "Infectious Diseases Institute, Makerere",
      "website": "",
      "contact": "bcastelnuovo@idi.co.ug",
      "added_by": "",
      "notes": "Started 2005"
      },
      {
        "id": 15,
      "region": "Multi",
      "location": "RSA, BF, Ghana and Kenya",
      "economic": "LMIC",
      "name_of_cohort": "AWI-Gen (H3Africa)",
      "type": "Cohort",
      "description": "",
      "area": "Agincourt, Nanoro, Navrongo, Soweto, DIMAMO and Nairobi",
      "HDSS": "Y",
      "biosamoles": "Yes",
      "N": "12500",
      "setting": "Urban, semi-urban and rural",
      "research": "Y",
      "networks": "H3Africa",
      "follow_up": "2012-ongoing",
      "institution": "University of the Witwatersrand",
      "website": "AWI-GEN 2: Genomic and Environmental Risk Factors for Cardiometabolic Disease in Africans � H3Africa; https://protect-eu.mimecast.com/s/I8XPCnO14crjr0AS99EdY?domaiNwits.ac.za/",
      "contact": "michele.ramsay@wits.ac.za",
      "added_by": "Michele Ramsay",
      "notes": "Started 2012"
      },
      {
        "id": 16,
      "region": "North",
      "location": "Egypt",
      "economic": "LMIC",
      "name_of_cohort": "A Longitudinal Study of Egyptian Healthy Aging (AL-SEHA)",
      "type": "Cohort",
      "description": "Household level longitudinal cohort",
      "area": "Nationally representative (Egypt)",
      "HDSS": "N",
      "biosamoles": "No",
      "N": "20000",
      "setting": "Rural and urban",
      "research": "Y",
      "networks": "HRS",
      "follow_up": "2022 (pilot)- Ongoing, next wave (wave 1, 2024)",
      "institution": "The American University in Cairo",
      "website": "www.aucegypt.edu",
      "contact": "Mohamed.Salama@gbhi.org",
      "added_by": "",
      "notes": ""
      },
      {
        "id": 17,
      "region": "South",
      "location": "Malawi",
      "economic": "LIC",
      "name_of_cohort": "Healthy Lives Malawi - Rural Karonga - HDSS",
      "type": "HDSS",
      "description": "Rural HDSS",
      "area": "Karonga District",
      "HDSS": "YES",
      "biosamoles": "N",
      "N": "45000",
      "setting": "Rural",
      "research": "Y",
      "networks": "INDEPTH, ALPHA, ANDLA, INSPIRE",
      "follow_up": "2002-ongoing",
      "institution": "Malawi Epidemiology and Intervention Research Unit",
      "website": "www.meiru.info",
      "contact": "albert.dube@meiru.mw",
      "added_by": "Mia Crampin",
      "notes": ""
      },
      {
        "id": 18,
      "region": "South",
      "location": "Malawi",
      "economic": "LIC",
      "name_of_cohort": "Healthy Lives Malawi - Urban - Lilongwe HDSS",
      "type": "HDSS",
      "description": "Urban HDSS",
      "area": "Lilongwe City",
      "HDSS": "Y",
      "biosamoles": "N",
      "N": "65000",
      "setting": "Urban",
      "research": "Y",
      "networks": "",
      "follow_up": "2022-ongoing",
      "institution": "Malawi Epidemiology and Intervention Research Unit",
      "website": "www.meiru.info",
      "contact": "albert.dube@meiru.mw",
      "added_by": "Mia Crampin",
      "notes": "baseline 2022"
      },
      {
        "id": 19,
      "region": "South",
      "location": "Malawi",
      "economic": "LIC",
      "name_of_cohort": "Healthy Lives Malawi - Rural LTC",
      "type": "Cohort",
      "description": "Long-term conditions cohort",
      "area": "Karonga District",
      "HDSS": "Karonga HDSS",
      "biosamoles": "Y",
      "N": "est 20000",
      "setting": "Rural",
      "research": "Y",
      "networks": "ANDLA",
      "follow_up": "2021-ongoing",
      "institution": "Malawi Epidemiology and Intervention Research Unit",
      "website": "www.meiru.info",
      "contact": "owen.nkoka@glasgow.ac.uk",
      "added_by": "Mia Crampin",
      "notes": "recruitment ongoing"
      },
      {
        "id": 20,
      "region": "South",
      "location": "Malawi",
      "economic": "LIC",
      "name_of_cohort": "Healthy Lives Malawi - Urban LTC",
      "type": "Cohort",
      "description": "Long-term conditions cohort",
      "area": "Lilongwe City",
      "HDSS": "Lilongwe HDSS",
      "biosamoles": "Y",
      "N": "est 25000",
      "setting": "Urban",
      "research": "Y",
      "networks": "ANDLA",
      "follow_up": "2022-ongoing",
      "institution": "Malawi Epidemiology and Intervention Research Unit",
      "website": "www.meiru.info",
      "contact": "owen.nkoka@glasgow.ac.uk",
      "added_by": "Mia Crampin",
      "notes": "recruitment ongoing"
      },
      {
        "id": 21,
      "region": "South",
      "location": "Malawi",
      "economic": "LIC",
      "name_of_cohort": "Generation Malawi",
      "type": "Birth Cohort",
      "description": "Birth Cohort",
      "area": "Karonga & Lilongwe",
      "HDSS": "Karonga & Lilongwe HDSS",
      "biosamoles": "Y",
      "N": "8000",
      "setting": "Rural and Urban",
      "research": "Y",
      "networks": "",
      "follow_up": "2022-ongoing",
      "institution": "Malawi Epidemiology and Intervention Research Unit",
      "website": "www.meiru.info",
      "contact": "wnakanga@exseed.ed.ac.uk",
      "added_by": "Mia Crampin",
      "notes": "recruitment ongoing"
      },
      {
        "id": 22,
      "region": "South",
      "location": "South Africa",
      "economic": "UMIC",
      "name_of_cohort": "AHRI HDSS",
      "type": "HDSS",
      "description": "Rural HDSS",
      "area": "Northern KwaZulu-Natal",
      "HDSS": "Y",
      "biosamoles": "Y",
      "N": "147616",
      "setting": "Rural",
      "research": "Y",
      "networks": "SAPRIN, ALPHA",
      "follow_up": "2000-ongoing",
      "institution": "Africa Health Research Institute",
      "website": "https://www.ahri.org/",
      "contact": "Thobeka.Mngomezulu@ahri.org",
      "added_by": "Kobus Herbst",
      "notes": ""
      },
      {
        "id": 23,
      "region": "South",
      "location": "South Africa",
      "economic": "UMIC",
      "name_of_cohort": "GRT-INSPIRED HDSS",
      "type": "HDSS",
      "description": "Urban",
      "area": "Gauteng (Hillbrow, Atteridgeville, Melusi)",
      "HDSS": "Y",
      "biosamoles": "N",
      "N": "75000",
      "setting": "Urban inner city high rise, formal and informal urban settlements",
      "research": "Y",
      "networks": "SAPRIN",
      "follow_up": "2020-ongoing",
      "institution": "Wits Health Consortium",
      "website": "",
      "contact": "David.Everatt@wits.ac.za",
      "added_by": "Kobus Herbst",
      "notes": "Reaching end of baseline survey"
      },
      {
        "id": 24,
      "region": "South",
      "location": "Zambia",
      "economic": "LIC",
      "name_of_cohort": "Kanyama",
      "type": "HDSS",
      "description": "Urban HDSS",
      "area": "Kanyama compound, Lusaka",
      "HDSS": "Y",
      "biosamoles": "Y",
      "N": "est 200,000",
      "setting": "Urban",
      "research": "Y",
      "networks": "INSPIRE",
      "follow_up": "2023",
      "institution": "Institute of Human Sciences",
      "website": "Not yet",
      "contact": "Richard Mutemwa :Richard.Mutemwa@LSHTM.ac.uk",
      "added_by": "Jim Todd",
      "notes": "New - Started in 2020"
      },
      {
        "id": 25,
      "region": "South",
      "location": "Zimbabwe",
      "economic": "LMIC",
      "name_of_cohort": "Manicaland",
      "type": "Cohort",
      "description": "Open Cohort HIV sero-survey",
      "area": "Manicaland (Mutasa, Makoni Nyanga)",
      "HDSS": "Y",
      "biosamoles": "Y",
      "N": "14000",
      "setting": "Rural",
      "research": "Y",
      "networks": "ALPHA",
      "follow_up": "1998",
      "institution": "Manicaland Centre for Public Health Research",
      "website": "Open cohort - MANICALAND CENTRE (manicalandhivproject.org)",
      "contact": "sajgregson@aol.com",
      "added_by": "",
      "notes": "Study sites have changed over time - 6 sites continuous throughout cohort, some sites dropped and 2 new urban sites added in 2018. No biosamoles have been collected since 2018/19 survey"
      },
      {
        "id": 26,
      "region": "West",
      "location": "Burkina Faso",
      "economic": "LIC",
      "name_of_cohort": "Nanoro HDSS",
      "type": "HDSS",
      "description": "Rural HDSS",
      "area": "Nanoro (Burkina Faso)",
      "HDSS": "Y",
      "biosamoles": "N",
      "N": "66500",
      "setting": "Rural HDSS",
      "research": "Y",
      "networks": "INDEPTH",
      "follow_up": "2009-ongoing",
      "institution": "Unit� de recherche clinique de Nanoro",
      "website": "CRUN",
      "contact": "kderra@crun.bf",
      "added_by": "Scoping doc",
      "notes": "20th round ongoing"
      },
      {
        "id": 27,
      "region": "West",
      "location": "Burkina Faso",
      "economic": "LIC",
      "name_of_cohort": "Ouagadougou HDSS",
      "type": "HDSS",
      "description": "Urban HDSS with verbal autopsy for cause of death",
      "area": "Ouagadougou city (Burkina Faso)",
      "HDSS": "Y",
      "biosamoles": "N",
      "N": "100000",
      "setting": "URBAN",
      "research": "Y",
      "networks": "INDEPTH",
      "follow_up": "2008-ongoing (one round every year)",
      "institution": "Institut Sup�rieur des Sciences de la Population /Universit� Joseph KI_ZERBO",
      "website": "www.issp.bf",
      "contact": "ouilidris@gmail.com ; iouili@issp.bf; lankyem@yahoo.fr; BLANKOANDE@issp.bf",
      "added_by": "Scoping doc",
      "notes": "Preparing for the the 13th round"
      },
      {
        "id": 28,
      "region": "West",
      "location": "Ghana",
      "economic": "LMIC",
      "name_of_cohort": "Kintampo HDSS",
      "type": "HDSS",
      "description": "Rural/Urban, Collects household-level longitudinal data of all the resident population in the catchment area.",
      "area": "Kintampo North Municipality and Kintampo South District",
      "HDSS": "Y",
      "biosamoles": "N",
      "N": "142977",
      "setting": "Rural",
      "research": "Y",
      "networks": "INDEPTH",
      "follow_up": "2003-ongoing",
      "institution": "Health Research Unit of Ghana Health Service",
      "website": "https://kintampo-hrc.org",
      "contact": "Grace.Manu@kintampo-hrc.org",
      "added_by": "Scoping doc",
      "notes": "Conducts VA of all recorded deaths. Also, coverage was extended to include Nkoranza and Techiman in 2018"
      },
      {"id": 29,
      "region": "West",
      "location": "Mali",
      "economic": "LMIC",
      "name_of_cohort": "Bamako HDSS",
      "type": "HDSS",
      "description": "Urban HDSS",
      "area": "Quartier of Banconi and Djicoroni Para",
      "HDSS": "HDSS",
      "biosamoles": "No",
      "N": "203043",
      "setting": "Urban",
      "research": "Y",
      "networks": "",
      "follow_up": "2007-ongoing",
      "institution": "Centre for Vaccine Development - Mali",
      "website": "www.cvd-mali.org",
      "contact": "uonwuche@som.umaryland.edu",
      "added_by": "",
      "notes": "Started in 2007"
      }
      ]
  };



  